# Generated by Django 4.2.2 on 2023-07-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedbook',
            name='district',
        ),
        migrations.RemoveField(
            model_name='postedbook',
            name='upazila',
        ),
    ]
