# Generated by Django 4.2.2 on 2023-07-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_postedbook_reader_postedbook_reader_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedbook',
            name='reader_status',
            field=models.CharField(choices=[('Posted', 'Posted'), ('Accept?', 'Accept?'), ('Accepted', 'Accepted'), ('Sent', 'Sent'), ('Sending', 'Sending'), ('Received', 'Received')], default='Posted Now', max_length=255),
        ),
    ]
