# Generated by Django 4.2.2 on 2023-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_postedbook_reader_alter_postedbook_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedbook',
            name='reader_status',
            field=models.CharField(choices=[('Posted Now', 'Posted Now'), ('Posted', 'Posted'), ('Accept?', 'Accept?'), ('Accepted', 'Accepted'), ('Sent', 'Sent'), ('Sending', 'Sending'), ('Received', 'Received')], default='Posted Now', max_length=255),
        ),
    ]
