# Generated by Django 4.2.2 on 2023-07-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_postedbook_reader_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedbook',
            name='requestor_status',
        ),
        migrations.AlterField(
            model_name='postedbook',
            name='reader_status',
            field=models.CharField(choices=[('Posted Now', 'Posted Now'), ('Posted', 'Posted'), ('Request Now', 'Request Now'), ('Accept?', 'Accept?'), ('Accepted', 'Accepted'), ('Contract', 'Contract'), ('Sent', 'Sent'), ('Sending', 'Sending'), ('Received', 'Received')], default='Posted Now', max_length=255),
        ),
    ]
