# Generated by Django 4.2.2 on 2023-07-25 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_remove_postedbook_requestor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedbook',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
