# Generated by Django 4.2.2 on 2023-07-25 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_remove_postedbook_reader_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedbook',
            name='book_position',
            field=models.CharField(choices=[('Posted Now', 'Posted Now'), ('Posted', 'Posted'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Contract', 'Contract'), ('Sending', 'Sending'), ('Received', 'Received')], default='Posted Now', max_length=255),
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=255)),
                ('posted_book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.postedbook')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
