# Generated by Django 4.2.2 on 2023-07-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_postedbook_book_position_bookrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrequest',
            old_name='position',
            new_name='status',
        ),
    ]
